#! /bin/sh

# so-care -- take care of .so files
# $Id: so-care,v 1.2 1998/07/10 21:36:02 cdua Exp cdua $
# Carlos Duarte, 960707/960707

# usage: so-care man-files... 
#    eg: so-care *

#
#	get files that contain .so to others
#
# 	the formers are the soer (sourcerer)
# 	laters are soed (sourced)
#
#	so-care finds all files containing .so's to the same file,
#	i.e. soer's that .so the same soed, then if that files
#	are not hardlinks to each others, keep one of them and
#	make all the others hardlinks to it
#
#	so, we will have only one file containing .so man1/foo.1 
#	and several hardlinks

#
# soed_soer will have the format: (soed soer )*
# and for repeated soed files, the respective soer cames sequently
# 
soed_soer=`egrep '^\.so' $* | sed 's,\([^:]*\):\.so.\(.*\),\2 \1,' | sort`

: ${soed_soer:?'No .so files found!'}

soer=`echo $soed_soer | sed 's, *[^ ]* \([^ ]*\),\1 ,g'`

# inode have the format: (inode soer)
#
inode=
for i in $soer; do 
	inode=$inode" "`ls -i $i`
done

echo $soed_soer $inode | awk '

BEGIN {
	RS = " "
	flg = 1
	i = 0
}

{
	if(flg == 1)
	{
		soed[i] = $1
		flg = 0
	}
	else if(flg == 0)
	{
		soer[i] = $1

		if(i && $1 == soer[0])
		{
			inode[0] = soed[i]
			i = 1
			flg = 2
		}
		else
		{
			i++
			flg = 1
		}
	}
	else if(flg == 2)
	{
		inode[i] = $1
		i++
		flg = 3
		next
	}
	else if(flg == 3)
	{
		flg = 2
		next
	}
}

END {
	max=i
	last_soed = soed[0]
	last_inode = inode[0]
	last_soer = soer[0]
	for(i = 1; i < max; i++)
	{
		if(soed[i] == last_soed)
		{
			if(inode[i] != last_inode)
			{
				#print "rm " soer[i] 
				print "ln -fv " last_soer " " soer[i]
			}
		}
		else
		{
			last_soed = soed[i]
			last_inode = inode[i]
			last_soer = soer[i]
		}
	}

	print "exit"

}' | sh
