#! /bin/sh 

# anytolz -- recompresses compressed files with lzip
# Carlos Duarte, 031029/090609

if test $# -eq 0 ; then
	echo "usage: $0 files"
	exit 1
fi

for i
do
	case $i in 
	*gz) P=gzip ;; 
	*bz2) P=bzip2 ;;
	*lzma) P=lzma ;;
	*) continue ;;
	esac
	dst="$(echo "$i" | sed 's/\(gz\|bz2\|lzma\)$//')"lz
	$P -dc "$i" | buffer | lzip > "$dst" && 
	touch -r "$i" "$dst" &&
	rm "$i"
done
